flowchart TD
    A(["Incoming message (poll/webhook)"]) --> B["@girae/inbounder"]
    B --> C["Is it a valid command (starts with / and bot handles it)?\n\nIs user banned?\n\nIs it an inline query or actual message?"]
    C -->|Not valid| F
    C -->|Inline query event| E
    C -->|Message event| E


    F([Ignore])
    E["@girae/commandeer"]

    E --> G{Command processor}
